spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: mysql
      
